import ProjectContainer from "@/components/Projects/ProjectContainer";
import React from "react";
import Layout from "@/components/Layout/layout";
import Head from "next/head";
import QuoteContainer from "@/components/Quotes/QuoteContainer";
import { prisma } from "@/pages/api/_prisma";

function Quote({
  quote,
  project,
  materials,
  sales_org,
  account_manager,
  dsm,
  customer,
}) {
  return (
    <Layout>
      <Head>
        <title>Quote Overview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QuoteContainer
        quote={quote}
        project={project}
        materials={materials}
        sales_org={sales_org}
        account_manager={account_manager}
        dsm={dsm}
        customer={customer}
      />
    </Layout>
  );
}

export default Quote;

export async function getServerSideProps({ params }) {
  const customer = await prisma.customer.findMany();

  const quote = await prisma.quote.findFirst({
    where: { id: Number(params.id) },
    include: {
      Customer: true,
      Employees_Quote_created_byToEmployees: true,
      Employees_Quote_modified_byToEmployees: true,
      Account_Manager: true,
      DSM: true,
    },
  });

  const project = await prisma.project.findFirst({
    where: { project_id: quote.project_id },
  });

  const sales_org = await prisma.sales_Org.findMany();
  const account_manager = await prisma.account_Manager.findMany({
    where: { sales_org_id: project.sales_org_id },
  });
  const dsm = await prisma.dSM.findMany({
    where: { sales_org_id: project.sales_org_id },
  });

  const materials = await prisma.material_Quoted.findMany({
    where: {
      permanent_quote_id: quote.quote_id,
      quote_version: quote.quote_version,
      is_active: true,
    },
    include: {
      Material: {
        include: {
          Material_Sales_Org: true,
        },
      },
    },
  });

  return {
    props: {
      quote: JSON.parse(JSON.stringify(quote)),
      project: JSON.parse(JSON.stringify(project)),
      materials: JSON.parse(JSON.stringify(materials)),
      sales_org: JSON.parse(JSON.stringify(sales_org)),
      account_manager: JSON.parse(JSON.stringify(account_manager)),
      dsm: JSON.parse(JSON.stringify(dsm)),
      customer: JSON.parse(JSON.stringify(customer)),
    },
  };
}
